[opener]
dolphin = [
	{ run = "dolphin -- %s1", desc = "Dolphin", for = "linux", orphan = true },
]

[open]
prepend_rules = [
	{ url = "*/", use = "dolphin" },
]

[plugin]
prepend_previewers = [
	{ mime = "image/*", run = "noop" },
]
prepend_preloaders = [
	{ mime = "image/*", run = "noop" },
]
